// generated by Fast Light User Interface Designer (fluid) version 1.0105

#ifndef trimp_fltk_h
#define trimp_fltk_h
#include <FL/Fl.H>
extern int progress_counter;
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *main_panel;
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_File_Chooser.H>
extern void fc_callback( char* filename);
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *tab_set_1;
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
extern Fl_Box *ref_diagram;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *smt_thk_o;
extern Fl_Value_Input *top_cu_thk_o;
extern Fl_Value_Input *lam1_thk_o;
extern Fl_Value_Input *lam1_er;
extern Fl_Value_Input *trace1_width_main_i;
extern Fl_Value_Input *trace_sep_main_i;
extern Fl_Value_Input *lam2_er;
extern Fl_Value_Input *lam2_thk_o;
extern Fl_Value_Input *bot_cu_thk_o;
extern Fl_Value_Input *smb_thk_o;
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *smt_enable;
extern Fl_Check_Button *top_plane_enable;
extern Fl_Check_Button *lam1_enable;
extern Fl_Check_Button *edge_diff;
extern Fl_Check_Button *coplanar_enable;
#include <FL/Fl_Choice.H>
extern Fl_Choice *sig1_cu_thickness;
extern Fl_Check_Button *lam2_enable;
extern Fl_Check_Button *fillerer_same;
extern Fl_Check_Button *lam2_same;
extern Fl_Check_Button *bot_plane_enable;
extern Fl_Check_Button *smb_enable;
extern Fl_Group *bitmap_drawing;
#include <FL/Fl_Scroll.H>
extern Fl_Scroll *scroll_bmp;
#include <FL/Fl_BMP_Image.H>
extern Fl_Box *current_bmp;
extern Fl_Group *log_output;
#include <FL/Fl_Browser.H>
extern Fl_Browser *main_log;
extern Fl_Button *btn_analyze;
#include <FL/Fl_Output.H>
extern Fl_Output *compute_status;
extern Fl_Scroll *field_plot_s;
extern Fl_Box *field_plot;
Fl_Double_Window* make_window();
extern Fl_Menu_Item menu_[];
#define import_values (menu_+1)
extern Fl_Menu_Item menu_sig1_cu_thickness[];
extern Fl_Button *about_close;
Fl_Double_Window* make_about_window();
Fl_Double_Window* make_config_window();
extern Fl_Double_Window* main_window;
extern Fl_Double_Window* about_window;
extern Fl_Double_Window* config_window;
extern Fl_File_Chooser* fc;
extern Fl_Group *sm_group;
extern Fl_Value_Input *sm_thickness;
extern Fl_Value_Input *sm_er;
extern Fl_Value_Input *sm_loss_tangent;
extern Fl_Value_Input *sm_open_x_off;
extern Fl_Value_Input *sm_open_x_w;
#include <FL/Fl_Value_Slider.H>
extern Fl_Value_Slider *sm_fill_type;
Fl_Double_Window* make_layer_sm_window();
extern Fl_Double_Window *cu_plane;
extern Fl_Group *cu_group;
extern Fl_Value_Input *cu_thickness;
extern Fl_Value_Input *cu_open_x_off;
extern Fl_Value_Input *cu_open_x_w;
extern Fl_Value_Input *cu_loss_tangent;
extern Fl_Value_Input *cu_filler_er;
Fl_Double_Window* make_layer_cu_plane_window();
extern Fl_Double_Window *laminate;
extern Fl_Group *lam_group;
extern Fl_Value_Input *lam_thickness;
extern Fl_Value_Input *lam_resin_er;
extern Fl_Value_Input *lam_glass_er;
extern Fl_Value_Input *lam_resin_content;
extern Fl_Value_Input *lam_loss_tangent;
Fl_Double_Window* make_layer_laminate_window();
extern Fl_Double_Window *signal;
extern Fl_Group *sig_group;
extern Fl_Value_Input *sig_thickness;
extern Fl_Value_Input *sig_trace_etchback;
extern Fl_Value_Input *sig_filler_er;
extern Fl_Value_Input *sig_loss_tangent;
extern Fl_Value_Input *sig_trace1_w;
extern Fl_Value_Input *sig_trace_separation;
extern Fl_Value_Input *sig_trace2_width;
Fl_Double_Window* make_layer_signal_window();
extern Fl_Check_Button *cop1_enable;
extern Fl_Value_Input *cop1_width;
extern Fl_Value_Input *cop1_separation;
extern Fl_Check_Button *cop2_enable;
extern Fl_Check_Button *cop2_symmetry;
extern Fl_Value_Input *cop2_width;
extern Fl_Value_Input *cop2_separation;
Fl_Double_Window* make_coplanar_input_window();
extern Fl_Double_Window* layer_smt;
extern Fl_Double_Window* layer_smb;
extern Fl_Double_Window* layer_top_plane;
extern Fl_Double_Window* layer_bot_plane;
extern Fl_Double_Window* layer_lam1;
extern Fl_Double_Window* layer_lam2;
extern Fl_Double_Window* layer_sig1;
extern Fl_Double_Window* layer_cop;
#endif
